# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=10, verbose_name='Passport'),
        ),
    ]
