# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0002_stprofile_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='stprofile',
            name='adress',
            field=models.TextField(blank=True, verbose_name='Adress'),
        ),
    ]
