# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsdb', '0003_stprofile_adress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stprofile',
            options={'verbose_name': '\u041f\u0440\u043e\u0444\u0456\u043b\u044c \u043a\u043e\u0440\u0438\u0441\u0442\u0443\u0432\u0430\u0447\u0430'},
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='adress',
            field=models.TextField(blank=True, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0430'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, default=b'', max_length=12, verbose_name='\u041c\u043e\u0431\u0456\u043b\u044c\u043d\u0438\u0439 \u0442\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
        migrations.AlterField(
            model_name='stprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=10, verbose_name='\u041f\u0430\u0441\u043f\u043e\u0440\u0442'),
        ),
    ]
